<?php

namespace RezerwacjePkpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassageRepository extends EntityRepository
{
}
